apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-k8s-yaml
spec:
  selector:
    matchLabels:
      app: spring-k8s-yaml
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-k8s-yaml
    spec:
      containers:
        - name: spring-k8s-yaml
          image: springk8s:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1010 # The port that the container is running on in the cluster